### PR TITLE
Bump bin-wrapper to version 4

### PR DESCRIPTION
**Pull request by realityking**
This should be good as a minor release.

### CODE REVIEW

**Comment by patsplat** [comment]
It doesn't work as a minor release pngquant-bin returns a BinWrapper, and bin-wrapper 4.x changes the public api.

That's at least part of why the post-installs script is failing.

**Comment by realityking** [comment]
Test fails because of this bug: https://github.com/kevva/bin-wrapper/pull/69

While bin-wrapper's public API did change, this module only returns the path. Thus no breaking change.

https://github.com/imagemin/pngquant-bin/blob/30d0f40e7866e10c5a24f785e0800e0d5013daaf/index.js#L1-L2

**Comment by LOK-Soft** [comment]
any progress here, or do we need to wait for kevva/bin-wrapper#69 ?
As I understand there is a test failing, which checks the api, but there is no need to have the unchanged api for our purpose... did I get this right?

**Comment by LOK-Soft** [comment]
kevva/bin-wrapper#69 was merged in version 4.0.1

**Comment by 1000ch** [comment]
@realityking 
`bin-wrapper` now use [Promise interface](https://github.com/kevva/bin-wrapper#usage), so `run()` returns Promise, so fix `install.js` like https://github.com/imagemin/gifsicle-bin/pull/100.

**Comment by LOK-Soft** [comment]
> @realityking
> `bin-wrapper` now use [Promise interface](https://github.com/kevva/bin-wrapper#usage), so `run()` returns Promise. Please also fix `install.js` like [imagemin/gifsicle-bin#100](https://github.com/imagemin/gifsicle-bin/pull/100).

I just opened a new PR with new `bin-wrapper` version 4.0.1 and Change to promise.

**Comment by 1000ch** [comment]
Fixed on #95, sorry 😢

**Pull request closed without merging**
